### PR TITLE
Fix links to Github in documentation

### PR DESCRIPTION
**Pull request by albinahlback**
-

### CODE REVIEW

**Comment by kalmarek** [comment]
very well, but the documentation is linked under a blue button just below the `GroupsCore` in the REAMDE, isn't it?

**Comment by albinahlback** [comment]
Oh, I've never used those buttons. You are right.

**Comment by kalmarek** [comment]
yeah, I'm not fan of linking to dev docs directly. I'll have to figure out how to create and deploy docs for each version

**Comment by albinahlback** [comment]
Let's do like this right now.

**Review by kalmarek — APPROVED** [review]

**Pull request merged**
